### ISSUE TITLE
hpm install - iterate over plugins array and install any not installed.

### ISSUE THREAD

**Issue by CrashyBang** [zeit/hpm#26]
I track my `.hyperterm.js` using a dotfiles repo and git.

Part of my install process is symlinking my `.hyperterm.js` to `~/.hyperterm.js` the problem is this doesn't automatically install any of my plugins and the next time I open HyperTerm it fails to find the uninstalled plugins, which makes sense.

I was wondering if `hpm install` with no params would look in my `.hyperterm.js` plugins array and install any missing plugins much like `npm install`.

If there is a better way to handle this let me know, I just though it made sense seeing as a lot of the functionality being implemented seems to be inspired by `npm`.

Cheers.

**Comment by matheuss** [comment]
Hey man,

I think this is not on the scope of `hpm`. When you change `~/.hyperterm.js`, HyperTerm detects the changes and installs/uninstall/etc the plugins/themes/etc as needed. If this is not working, you might want to open an issue [there](https://github.com/zeit/hyperterm/issues) :P
