### ISSUE TITLE
Trouble Running After Initial Installation

### ISSUE THREAD

**Issue by SMLMRKHLMS** [zeit/hpm#37]
After running `npm install -g hpm-cli && hpm help` I get the following error:

I am running `node v6.4.0` and `npm v3.10.3`

![screen shot 2016-10-06 at 10 29 55 am](https://cloud.githubusercontent.com/assets/5240571/19156435/db0b46a0-8baf-11e6-850b-a55ac7ec8f56.png)

**Comment by chrisdothtml** [comment]
What are the contents of your `~/.hyper.js` file when this happens?

**Comment by Orangetronic** [comment]
I get this error if I don't have a `packages: [],` item in my .hyper.js
