### ISSUE TITLE
Should work with new version named "hyper"

### ISSUE THREAD

**Issue by revelt** [zeit/hpm#40]
When I updated Hyperterm its name has changed and `hpm` doesn't work anymore.
![screen shot 2016-10-07 at 10 38 53](https://cloud.githubusercontent.com/assets/8344688/19185610/434f4d9a-8c7a-11e6-8b56-ab0811184dba.png)

Either `hpm` should support both names or only `hyper`, but then prompt to update?

**Comment by abestic9** [comment]
This has been covered in pull request https://github.com/zeit/hpm/pull/38.
