### ISSUE TITLE
Use the package keyword 'hyper-plugin'

### ISSUE THREAD

**Issue by chrisdwheatley** [zeit/hpm#41]
I'm currently working on a bot to send pull requests to all plugins to update their keywords from 'hyperterm' to a new, more relevant keyword.

Is there a new agreed keyword which all plugins should add? If not then I'm proposing 'hyper-plugin' as mentioned by @leo [here](https://github.com/zeit/hpm/pull/38#issuecomment-252364031).

Would be good to get some feedback on this then we can get the ball rolling on sending out PR's to all plugins.

**Comment by matheuss** [comment]
cc @leo @rauchg

**Comment by chrisdwheatley** [comment]
Here's an example of what the bot will do - https://github.com/chrisdwheatley/hyper-plugin-test/pull/1

It's still work in progress but mostly there. Bot name and messaging can all be amended as desired.

**Comment by chrisdwheatley** [comment]
Any further thoughts on this?

**Comment by leo** [comment]
`hyper-plugin` (themes are plugins as well) 😊
