### ISSUE TITLE
Error with first use

### ISSUE THREAD

**Issue by eladcandroid** [zeit/hpm#56]
I'm getting this error when trying to use it after the installation:

![image](https://cloud.githubusercontent.com/assets/13297000/21132173/47dacb52-c11b-11e6-8774-f68ec071709a.png)

(Windows 7, NPM v2.15.9)

**Comment by eladcandroid** [comment]
I have the same error also after upgrading to NPM v4.0.3

**Comment by alisonmonteiro** [comment]
Hey @eladcandroid

Could you please try a NodeJS version >=  6.0.0?
[This guy](https://github.com/zeit/hpm/issues/55#issuecomment-266557912) had the same issue.

😄

**Comment by eladcandroid** [comment]
Now works after update node to 6.9.2. Thanks!

**Comment by samlroberts** [comment]
Just ran into this same problem. 

Will the required node version be bumped in package.json?
