### ISSUE TITLE
Syntax Error: Unexpected Token

### ISSUE THREAD

**Issue by alechp** [zeit/hpm#57]
Vanilla install of hpm-cli.

**OSX**: 10.12.1
**Install path**: /usr/local/lib/node_modules
**Error**:

![screen shot 2016-12-13 at 7 48 04 am](https://cloud.githubusercontent.com/assets/3058939/21147051/8d843156-c108-11e6-8965-5a5b6768ef6a.png)

**Comment by alisonmonteiro** [comment]
Duplicated with #56
