### ISSUE TITLE
Doesn't seem to work at all.

### ISSUE THREAD

**Issue by genu** [zeit/hpm#72]
First time trying hyper and hpm, forgive me if I missed a step in setting up.

I'm trying to test it out with the example given in the README.md, but I get this:

![image](https://cloud.githubusercontent.com/assets/928780/22571002/ccad4d8c-e96b-11e6-8012-917e9ece5c84.png)

Did I do something wrong, or is this a bug?

**Comment by lizenas** [comment]
This happens to me too.

**Comment by jondcallahan** [comment]
I downgraded to `1.4.0` and it is working again

**Comment by Tristan971** [comment]
Can confirm it happening here too (Arch x64 and latest hyperterm + zsh + oh-my-zsh)

**Comment by Barbayar** [comment]
it's happening on my environment as well.
```
doge:local barbayar.dashzeveg$ node -v
v7.5.0
doge:local barbayar.dashzeveg$ npm -v
4.1.2
doge:local barbayar.dashzeveg$ hpm -v
2.0.0
```

**Comment by 8-uh** [comment]
Every command is broken save for `$ hpm ls`

**Comment by DustinJSilk** [comment]
Nothing works for me either.

```
Dustins-MacBook-Pro:~ dustinjsilk$ node -v
v6.6.0
Dustins-MacBook-Pro:~ dustinjsilk$ npm -v
3.10.3
Dustins-MacBook-Pro:~ dustinjsilk$ hpm -v
2.0.0
```

**Comment by crutchcorn** [comment]
Just letting you guys know:
@ringohub has fixed this issue with the help page showing up all the time with #74

**Comment by eamodio** [comment]
Now it just needs to be released ;)

**Comment by brooksyari** [comment]
Another one here. LS only works well.

**Comment by crutchcorn** [comment]
If you guys are looking for a fix to the problems in 2.0.0 before release, my fork is functioning as expected.

**Comment by nealoke** [comment]
Same issue

**Comment by jonaswindey** [comment]
+1

**Comment by daniellacosse** [comment]
+1

**Comment by andrewmclagan** [comment]
Any timeline for a release?

**Comment by possebon** [comment]
This happens with me too. Running Hyper.js 1.1.0.1408 on macOS Sierra, hpm -v 2.0.0

**Comment by JadoJodo** [comment]
Same issue.

**Comment by crutchcorn** [comment]
Guys, this is a known issue and can be explained in great technical detail. There are already fixes in my fork and @ringohub's fork (though there are more issues that prevent installing that aren't fixed on their fork). Let's please prevent more `+1`s or `Me too`s.

**Comment by rauchg** [comment]
We'll merge really soon. Thanks @crutchcorn <3

**Comment by crutchcorn** [comment]
Was just about to work on #78 (finally found time), does this mean feature freeze as things are merged in? How should I proceed?

**Comment by ClemMakesApps** [comment]
> We'll merge really soon. Thanks @crutchcorn <3
> We'll also release this as hyper version soon and auto-install it with the terminal

Excited for this @rauchg! Any ETA?

**Comment by jacola** [comment]
copy paste gets fixed, and then this breaks.... :(

**Comment by Global-Open-Source** [comment]
well I also have this bug, newest version of both Hyper and hpm

**Comment by crutchcorn** [comment]
Pardon, @matheuss, but hpm will continue to not work until my pull request is merged. There are more problems with the plugins array was handled internally moving to the 2.0.0 update

**Comment by drorata** [comment]
What version of `npm` has to be installed?
