### ISSUE TITLE
normalized ast breaks ability to push (or split) items from plugins

### ISSUE THREAD

**Issue by crutchcorn** [zeit/hpm#75]
I have been working on making a Pull Request (and understanding) hpm. I have noticed that hpm install and hpm uninstall do not work (and only run after #74 is added). This is very likely due to the added oldConf file. While that was added, isInstalled was not updated to reflect. I'll be looking into this and submitting a pull request with a fix

**Comment by ringohub** [comment]
I have same issue. I investigate it too 😃.

**Comment by crutchcorn** [comment]
@ringohub would you generally agree with my thoughts on the cause of the problem? I'm going to be looking more into it tonight. I'll likely do a pull request. Can have all the good ones go to one person. ;)

**Comment by crutchcorn** [comment]
I think I may have found the ACTUAL problem:
```
function save() {
	return pify(fs.writeFile)(fileName, recast.print(parsedFile).code, 'utf8');
}
```
This is the function that is called for `uninstall` and `install`. Notice how all it does is save the `parsedFile` code to `fileName` (which is the new config file btw, there is no checks for old config files really anywhere). This function needs to be refactored to take in a variable to remove/add a plugin from the config file

**Comment by crutchcorn** [comment]
Okay, I'm clearly not smart. I wasn't aware that when you modified plugin, you're modifying the other parts (ie `parsedFile`) with it. Because of this, when 7dcf4200283d82581a411ea86805da8e378174c0 was pushed through, the `splice()` and `push()` from `uninstall()` and `install()` (respectively) were attempting to modify a straight list of items rather than a recast list of items, therefore leaving `parsedFile` as it was before

**Comment by ringohub** [comment]
However, I'm not starting to it. And I can't get time for investigating until week end.
You are fixing it now(thank you). I wait 😄 😄 😄 .
