### ISSUE TITLE
Cannot read property of 'popup' of null

### ISSUE THREAD

**Issue by manizm** [zeit/hpm#94]
So, whenever I am trying to open "hamburger menu", I am getting this error. I cant open new tabs either..
![hyper-popup-error](https://user-images.githubusercontent.com/17122974/31306328-ba473604-ab4d-11e7-8b8e-68a981bd3d72.png)

I am not sure what is the issue. I am getting the same error on my work machine as well. Both running windows 10.

**Comment by MAPESO** [comment]
@manizm could you tell me which version of Hyper you are using and the **hyper.js** file 😄

**Comment by MAPESO** [comment]
@manizm This problem has to go in the Hyper repository.  Your problem has nothing to do with hpm😅
https://github.com/zeit/hyper

**Comment by manizm** [comment]
oh ok, sorry. Will post it there, Thanks!
